language: java
jdk:
  - openjdk19
services: docker
before_install:
  - chmod +x mvnw

script:
  - mvn clean install
  - docker build -t yams:appariement ./appariement
  - docker build -t yams:joueur ./joueur
  - docker build -t yams:joueur2 ./joueur
  - docker build -t yams:hebergeur ./hebergeur
  - docker-compose up &
  - sleep 30
  - docker-compose down