version: '3'
services:
  appariement:
    image: yams:appariement
    container_name: appariement
    ports:
      - 8080:8080
    networks:
      testing_net:
        ipv4_address: 172.28.0.253

  joueur:
    image: yams:joueur
    environment:
      - SERVER_IP=http://172.28.0.253:8080/
      - SERVER_PORT=8082
    depends_on:
      - appariement
    networks:
      testing_net:
        ipv4_address: 172.28.0.3

  hebergeur:
    image: yams:hebergeur
    environment:
      - SERVER_IP=http://172.28.0.253:8080/
      - SERVER_PORT=8091
    depends_on:
      - appariement


  proba:
    image: yams:proba
    depends_on:
      - appariement

networks:
  testing_net:
    ipam:
      config:
        - subnet: 172.28.0.0/16