version: '3'

services:

  ####################Appariement####################
  appariement:
    image: yams:appariement
    container_name: appariement
    networks:
      testing_net:
        ipv4_address: 172.28.0.253
      #depends_on:
      #- client

  ####################joueur####################
  joueur:
    image: yams:joueur
    # container_name: player
    environment:
      - SERVER_IP=172.28.0.253
    networks:
      testing_net:
      #  ipv4_address: 172.28.0.3

  ####################hebergeur####################
  hebergeur:
    image: yams:hebergeur
    # container_name: partie
    environment:
      - SERVER_IP=172.28.0.253
    networks:
      testing_net:
      #  ipv4_address: 172.28.0.3

  ####################proba####################
  proba:
    image: yams:proba
    # container_name: proba
    environment:
      - SERVER_IP=172.28.0.253
    networks:
      testing_net:
        ipv4_address: 172.28.0.252





networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16